function photo(id) {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;
}

const products = [
  {
    name: 'Trail Backpack',
    slug: 'trail-backpack',
    description: 'A padded everyday backpack with a laptop sleeve and weather-resistant fabric. Built for commute and weekend trips.',
    price: 89,
    comparePrice: 120,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1553062407-98eeb64c6a62'),
    rating: 4.8,
    reviewCount: 312,
    stock: 24,
    deal: true,
    featured: true
  },
  {
    name: 'City Daypack',
    slug: 'city-daypack',
    description: 'Compact daypack with a clean profile, front pocket, and adjustable straps.',
    price: 64,
    comparePrice: 82,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1547949003-9792a18a2601'),
    rating: 4.6,
    reviewCount: 148,
    stock: 30,
    deal: true,
    featured: false
  },
  {
    name: 'Leather Tote',
    slug: 'leather-tote',
    description: 'Structured tote in smooth leather. Fits a 14-inch laptop, charger, and a book.',
    price: 129,
    comparePrice: 160,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1590874103328-eac38a683ce7'),
    rating: 4.7,
    reviewCount: 96,
    stock: 14,
    deal: false,
    featured: true
  },
  {
    name: 'Weekender Duffel',
    slug: 'weekender-duffel',
    description: 'Soft duffel with shoe compartment and detachable shoulder strap.',
    price: 98,
    comparePrice: 130,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1622560480605-d83c853bc5c3'),
    rating: 4.5,
    reviewCount: 77,
    stock: 18,
    deal: true,
    featured: false
  },
  {
    name: 'Studio Headphones',
    slug: 'studio-headphones',
    description: 'Over-ear headphones with deep bass and plush cushions for long listening sessions.',
    price: 149,
    comparePrice: 199,
    category: 'Audio',
    unit: '1 pc',
    image: photo('1505740420928-5e560c06d30e'),
    rating: 4.9,
    reviewCount: 540,
    stock: 22,
    deal: true,
    featured: true
  },
  {
    name: 'Wireless Earbuds',
    slug: 'wireless-earbuds',
    description: 'Pocket earbuds with a charging case, touch controls, and a secure fit.',
    price: 79,
    comparePrice: 99,
    category: 'Audio',
    unit: '1 pair',
    image: photo('1590658268037-6bf12165a8df'),
    rating: 4.6,
    reviewCount: 421,
    stock: 40,
    deal: true,
    featured: true
  },
  {
    name: 'Portable Speaker',
    slug: 'portable-speaker',
    description: 'Compact Bluetooth speaker with a full sound and a fabric wrap.',
    price: 69,
    comparePrice: 89,
    category: 'Audio',
    unit: '1 pc',
    image: photo('1608043152269-423dbba4e7e1'),
    rating: 4.7,
    reviewCount: 233,
    stock: 28,
    deal: false,
    featured: true
  },
  {
    name: 'White Over-Ear Headphones',
    slug: 'white-over-ear-headphones',
    description: 'Lightweight over-ear pair with a clear mic and fold-flat design.',
    price: 119,
    comparePrice: 149,
    category: 'Audio',
    unit: '1 pc',
    image: photo('1484704849700-f032a568e944'),
    rating: 4.5,
    reviewCount: 164,
    stock: 19,
    deal: true,
    featured: false
  },
  {
    name: 'Classic Wristwatch',
    slug: 'classic-wristwatch',
    description: 'Slim analog watch with a leather strap and a readable dial.',
    price: 159,
    comparePrice: 210,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1524805444758-089113d48a6d'),
    rating: 4.8,
    reviewCount: 188,
    stock: 16,
    deal: true,
    featured: true
  },
  {
    name: 'Steel Chronograph',
    slug: 'steel-chronograph',
    description: 'Stainless steel watch with a three-hand chronograph layout.',
    price: 189,
    comparePrice: 240,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1523275335684-37898b6baf30'),
    rating: 4.7,
    reviewCount: 142,
    stock: 12,
    deal: false,
    featured: true
  },
  {
    name: 'Smart Watch',
    slug: 'smart-watch',
    description: 'Everyday smart watch with heart-rate tracking, notifications, and a two-day battery.',
    price: 179,
    comparePrice: 229,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1579586337278-3befd40fd17a'),
    rating: 4.6,
    reviewCount: 376,
    stock: 21,
    deal: true,
    featured: false
  },
  {
    name: 'Mirrorless Camera',
    slug: 'mirrorless-camera',
    description: 'Compact mirrorless body with a fast kit lens for travel and street photos.',
    price: 699,
    comparePrice: 849,
    category: 'Cameras',
    unit: '1 kit',
    image: photo('1516035069371-29a1b244cc32'),
    rating: 4.9,
    reviewCount: 201,
    stock: 8,
    deal: true,
    featured: true
  },
  {
    name: 'Travel Camera',
    slug: 'travel-camera',
    description: 'Pocket camera with a zoom lens and simple auto mode for trips.',
    price: 329,
    comparePrice: 399,
    category: 'Cameras',
    unit: '1 pc',
    image: photo('1502920917128-1aa500764cbd'),
    rating: 4.5,
    reviewCount: 119,
    stock: 11,
    deal: true,
    featured: false
  },
  {
    name: 'Instant Camera',
    slug: 'instant-camera',
    description: 'Instant-print camera for parties and desk photos. Film sold separately.',
    price: 99,
    comparePrice: 129,
    category: 'Cameras',
    unit: '1 pc',
    image: photo('1526170375885-4d8ecf77b99f'),
    rating: 4.4,
    reviewCount: 88,
    stock: 15,
    deal: false,
    featured: true
  },
  {
    name: 'Ceramic Vase',
    slug: 'ceramic-vase',
    description: 'Matte ceramic vase with a narrow neck. Looks right on a shelf or desk.',
    price: 42,
    comparePrice: 58,
    category: 'Home',
    unit: '1 pc',
    image: photo('1578500494198-246f612d3b3d'),
    rating: 4.6,
    reviewCount: 73,
    stock: 26,
    deal: true,
    featured: true
  },
  {
    name: 'Desk Plant',
    slug: 'desk-plant',
    description: 'A small leafy plant in a ceramic pot. Easy light, easy care.',
    price: 28,
    comparePrice: 36,
    category: 'Home',
    unit: '1 pc',
    image: photo('1485955900006-10f4d324d411'),
    rating: 4.7,
    reviewCount: 154,
    stock: 34,
    deal: false,
    featured: true
  },
  {
    name: 'Arc Table Lamp',
    slug: 'arc-table-lamp',
    description: 'Warm table lamp with a linen shade for a reading corner.',
    price: 74,
    comparePrice: 96,
    category: 'Home',
    unit: '1 pc',
    image: photo('1507473885765-e6ed057f782c'),
    rating: 4.5,
    reviewCount: 61,
    stock: 13,
    deal: true,
    featured: false
  },
  {
    name: 'Round Sunglasses',
    slug: 'round-sunglasses',
    description: 'Lightweight round frames with UV protection and a slim case.',
    price: 48,
    comparePrice: 65,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1511499767150-a48a237f0083'),
    rating: 4.4,
    reviewCount: 210,
    stock: 36,
    deal: true,
    featured: false
  },
  {
    name: 'Leather Wallet',
    slug: 'leather-wallet',
    description: 'Slim bifold wallet with card slots and a hidden coin pocket.',
    price: 39,
    comparePrice: 52,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1627123424574-724758594e93'),
    rating: 4.6,
    reviewCount: 97,
    stock: 29,
    deal: false,
    featured: true
  },
  {
    name: 'Steel Water Bottle',
    slug: 'steel-water-bottle',
    description: 'Insulated bottle that keeps drinks cold for a workday. 750 ml.',
    price: 32,
    comparePrice: 42,
    category: 'Accessories',
    unit: '750 ml',
    image: photo('1602143407151-7111542de6e8'),
    rating: 4.8,
    reviewCount: 268,
    stock: 44,
    deal: true,
    featured: false
  },
  {
    name: 'Canvas Messenger',
    slug: 'canvas-messenger',
    description: 'A flap messenger with a padded laptop pocket and an adjustable strap.',
    price: 78,
    comparePrice: 99,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1548036328-c9fa89d128fa'),
    rating: 4.6,
    reviewCount: 121,
    stock: 20,
    deal: true,
    featured: false
  },
  {
    name: 'Mini Crossbody',
    slug: 'mini-crossbody',
    description: 'A small leather crossbody for phone, keys, and a card case.',
    price: 54,
    comparePrice: 72,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1591561954557-26941169b49e'),
    rating: 4.5,
    reviewCount: 86,
    stock: 27,
    deal: false,
    featured: true
  },
  {
    name: 'Rolling Cabin Bag',
    slug: 'rolling-cabin-bag',
    description: 'Carry-on roller with a front pocket and a telescoping handle.',
    price: 149,
    comparePrice: 189,
    category: 'Bags',
    unit: '1 pc',
    image: photo('1565026057447-bc90a3dceb87'),
    rating: 4.7,
    reviewCount: 64,
    stock: 9,
    deal: true,
    featured: false
  },
  {
    name: 'Desk Headphones',
    slug: 'desk-headphones',
    description: 'Closed-back headphones for calls and music at a desk.',
    price: 99,
    comparePrice: 129,
    category: 'Audio',
    unit: '1 pc',
    image: photo('1618366712010-f4ae9c647dcb'),
    rating: 4.6,
    reviewCount: 203,
    stock: 18,
    deal: true,
    featured: true
  },
  {
    name: 'Bookshelf Speaker',
    slug: 'bookshelf-speaker',
    description: 'A single compact speaker with a warm, room-filling sound.',
    price: 129,
    comparePrice: 160,
    category: 'Audio',
    unit: '1 pc',
    image: photo('1545454675-3531b543be5d'),
    rating: 4.8,
    reviewCount: 91,
    stock: 12,
    deal: false,
    featured: false
  },
  {
    name: 'Noise-Blocking Earbuds',
    slug: 'noise-blocking-earbuds',
    description: 'In-ear buds with a tight seal for commutes and flights.',
    price: 59,
    comparePrice: 79,
    category: 'Audio',
    unit: '1 pair',
    image: photo('1590658165737-15a047b8d3f8'),
    rating: 4.4,
    reviewCount: 177,
    stock: 33,
    deal: true,
    featured: false
  },
  {
    name: 'Field Watch',
    slug: 'field-watch',
    description: 'A simple field watch with a canvas strap and luminous hands.',
    price: 139,
    comparePrice: 175,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1522312346375-d1a52e2b99b3'),
    rating: 4.7,
    reviewCount: 110,
    stock: 14,
    deal: true,
    featured: true
  },
  {
    name: 'Gold-Tone Dress Watch',
    slug: 'gold-tone-dress-watch',
    description: 'A slim dress watch with a polished case and a leather strap.',
    price: 169,
    comparePrice: 220,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1434056886845-dac89ffe9b56'),
    rating: 4.5,
    reviewCount: 72,
    stock: 10,
    deal: false,
    featured: false
  },
  {
    name: 'Sport Smart Band',
    slug: 'sport-smart-band',
    description: 'A light fitness band for steps, sleep, and phone alerts.',
    price: 49,
    comparePrice: 69,
    category: 'Watches',
    unit: '1 pc',
    image: photo('1575311373937-040b8e1fd5b6'),
    rating: 4.3,
    reviewCount: 256,
    stock: 40,
    deal: true,
    featured: false
  },
  {
    name: 'Prime Lens Camera',
    slug: 'prime-lens-camera',
    description: 'A compact camera body paired with a bright 35mm-style prime lens.',
    price: 549,
    comparePrice: 649,
    category: 'Cameras',
    unit: '1 kit',
    image: photo('1452780212940-6f5c0d14d848'),
    rating: 4.8,
    reviewCount: 84,
    stock: 6,
    deal: true,
    featured: true
  },
  {
    name: 'Action Camera',
    slug: 'action-camera',
    description: 'A small rugged camera for bikes, hikes, and desk timelapses.',
    price: 199,
    comparePrice: 249,
    category: 'Cameras',
    unit: '1 pc',
    image: photo('1510127034890-ba27508e9f1c'),
    rating: 4.6,
    reviewCount: 133,
    stock: 17,
    deal: false,
    featured: false
  },
  {
    name: 'Camera Sling',
    slug: 'camera-sling',
    description: 'A padded sling that holds a camera body and one extra lens.',
    price: 68,
    comparePrice: 86,
    category: 'Cameras',
    unit: '1 pc',
    image: photo('1516035069371-29a1b244cc32'),
    rating: 4.5,
    reviewCount: 58,
    stock: 22,
    deal: true,
    featured: false
  },
  {
    name: 'Linen Throw',
    slug: 'linen-throw',
    description: 'A washed linen throw for a sofa or the foot of a bed.',
    price: 46,
    comparePrice: 62,
    category: 'Home',
    unit: '1 pc',
    image: photo('1616486338812-3dadae4b4ace'),
    rating: 4.6,
    reviewCount: 49,
    stock: 19,
    deal: false,
    featured: true
  },
  {
    name: 'Oak Side Table',
    slug: 'oak-side-table',
    description: 'A small oak table for a lamp, a book, and a cup.',
    price: 120,
    comparePrice: 155,
    category: 'Home',
    unit: '1 pc',
    image: photo('1532372320572-cda25653a26d'),
    rating: 4.7,
    reviewCount: 41,
    stock: 8,
    deal: true,
    featured: false
  },
  {
    name: 'Scented Candle',
    slug: 'scented-candle',
    description: 'A soy candle with a cedar and citrus scent. Burns about 40 hours.',
    price: 24,
    comparePrice: 32,
    category: 'Home',
    unit: '220 g',
    image: photo('1603006905003-be475563bc59'),
    rating: 4.8,
    reviewCount: 190,
    stock: 50,
    deal: true,
    featured: false
  },
  {
    name: 'Aviator Sunglasses',
    slug: 'aviator-sunglasses',
    description: 'Metal aviator frames with dark lenses and a hard case.',
    price: 58,
    comparePrice: 76,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1572635196237-14b3f281503f'),
    rating: 4.5,
    reviewCount: 144,
    stock: 31,
    deal: true,
    featured: true
  },
  {
    name: 'Canvas Cap',
    slug: 'canvas-cap',
    description: 'An unstructured cotton cap with an adjustable strap.',
    price: 22,
    comparePrice: 28,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1521369909029-2afed882baee'),
    rating: 4.4,
    reviewCount: 87,
    stock: 42,
    deal: false,
    featured: false
  },
  {
    name: 'Card Holder',
    slug: 'card-holder',
    description: 'A four-card leather sleeve that fits a front pocket.',
    price: 29,
    comparePrice: 38,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1627123424574-724758594e93'),
    rating: 4.6,
    reviewCount: 63,
    stock: 25,
    deal: true,
    featured: false
  },
  {
    name: 'Travel Umbrella',
    slug: 'travel-umbrella',
    description: 'A compact umbrella that folds into a bag side pocket.',
    price: 26,
    comparePrice: 34,
    category: 'Accessories',
    unit: '1 pc',
    image: photo('1531956531700-dc0ee0f1f9a5'),
    rating: 4.3,
    reviewCount: 52,
    stock: 37,
    deal: false,
    featured: false
  }
];

module.exports = products;
